export type QuestionInfo = {
  ID: string;
  title: string;
  top?: string;
  bottom?: string;
  tooltip?: string;
};

export type GroupInfo = {
  title: string;
  questions: Array<QuestionInfo>;
};

export const questionData: Array<GroupInfo> = [
  {
    title: "Sexual Activity",
    questions: [
      {
        ID: "AA",
        title: "Anal sex",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AB",
        title: "Anal plug (public, under clothes)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "AC",
        title: "Anal plug (in private, under clothes)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "AD",
        title: "Anal plugs (small)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "AE",
        title: "Anal plugs (large)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "AF",
        title: "Anal beads",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AG",
        title: "Vaginal sex",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AH",
        title: "Dilation",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AI",
        title: "Dildos",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AJ",
        title: "Figging/radishing",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AK",
        title: "Strap-on-dildos (penetrated by)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AL",
        title: "Strap-on-dildos (sucking on)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AM",
        title: "Strap-on-dildos (wearing)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "AN",
        title: "Vibrator on genitals",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "AO",
        title: "Masturbation",
        top: "Watching Partner",
        bottom: "Masturbating",
      },
      {
        ID: "AP",
        title: "Hand jobs",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "AQ",
        title: "Fingering",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AR",
        title: "Fellatio",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "AS",
        title: "Cunnilingus",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "AT",
        title: "Face Sitting",
        top: "Sitting",
        bottom: "Being Sit Upon",
      },
      {
        ID: "AU",
        title: "Oral/anal play (rimming)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "AV",
        title: "Speculums (anal)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "AW",
        title: "Speculums (vaginal)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "AX",
        title: "Fisting (anal)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AY",
        title: "Fisting (vaginal)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "AZ",
        title: "Urethral Sounds (metal)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "Aa",
        title: "Urethral Sounds (silicone / flexible)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "Ab",
        title: "Swallowing semen",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "Ac",
        title: "Snowballing",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ad",
        title: "Cumming on partner (general)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ae",
        title: "Cumming on partner (face)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Af",
        title: "Cumming on partner (chest)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ag",
        title: "Cumming on partner (body)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ah",
        title: "Cumming inside partner (mouth)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ai",
        title: "Cumming inside partner (vagina)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Aj",
        title: "Cumming inside partner (ass)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ak",
        title: "Double penetration (oral and vaginal)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "Al",
        title: "Double penetration (oral and anal)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "Am",
        title: "Double penetration (vaginal and anal)",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "An",
        title: "Triple penetration",
        top: "Penetrating",
        bottom: "Being Penetrated",
      },
      {
        ID: "Ao",
        title: "Group sex",
      },
      {
        ID: "Ap",
        title: "Orgies",
      },
      {
        ID: "Aq",
        title: "Gangbangs",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ar",
        title: "Threesomes (two male, one female)",
      },
      {
        ID: "As",
        title: "Threesomes (one male, two female)",
      },
      {
        ID: "At",
        title: "Threesomes (same sex)",
      },
      {
        ID: "Au",
        title: "Swapping (with one other couple)",
      },
      {
        ID: "Av",
        title: "Swinging (multiple couples)",
      },
    ],
  },
  {
    title: "Fetishes, Fantasies, and General Roleplay",
    questions: [
      {
        ID: "CA",
        title: "Hypnotism",
        top: "Hypnotizing",
        bottom: "Being Hypnotized",
      },
      {
        ID: "CB",
        title: "Mind control",
        top: "Controlling",
        bottom: "Being Controlled",
      },
      {
        ID: "CC",
        title: "Rituals",
      },
      {
        ID: "CD",
        title: "Initiation rites",
      },
      {
        ID: "CE",
        title: "Kidnapping",
        top: "Kidnapper",
        bottom: "Victim",
      },
      {
        ID: "CF",
        title: "Religious scenes",
      },
      {
        ID: "CG",
        title: "Prison scenes",
      },
      {
        ID: "CH",
        title: "Medical scenes",
      },
      {
        ID: "CI",
        title: "Schoolroom scenes",
      },
      {
        ID: "CJ",
        title: "Interrogation",
        top: "Interrogator",
        bottom: "Being Interrogated",
      },
      {
        ID: "CK",
        title: "Fantasy scenarios (pirates, aliens, vampires, etc) ",
      },
      {
        ID: "CL",
        title: "Examinations (physical)",
      },
      {
        ID: "CM",
        title: "Castration fantasy",
      },
      {
        ID: "CN",
        title: "Catheterization",
      },
      {
        ID: "CO",
        title: "Fantasy abandonment",
      },
      {
        ID: "CP",
        title: "Fantasy gang-rape",
        top: "Doing",
        bottom: "Receiving",
      },
      {
        ID: "CQ",
        title: "Fantasy rape",
        top: "Doing",
        bottom: "Receiving",
      },
      {
        ID: "CR",
        title: "Fear play",
      },
      {
        ID: "CS",
        title: "Gun play",
      },
      {
        ID: "CT",
        title: "Whore play",
      },
      {
        ID: "CU",
        title: "Incest fantasy/roleplay",
      },
      {
        ID: "CV",
        title: "Wrestling",
      },
      {
        ID: "CW",
        title: "Masks",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "CX",
        title: "Gas masks",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "CY",
        title: "Feathers",
      },
      {
        ID: "CZ",
        title: "Lingerie",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Ca",
        title: "Panties",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Cb",
        title: "Spandex clothing",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Cc",
        title: "Rubber/latex clothing",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Cd",
        title: "Leather clothing",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Ce",
        title: "Uniforms",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Cf",
        title: "Corsets (trained waist reduction)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Cg",
        title: "Corsets (wearing casually)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Ch",
        title: "High heels",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Ci",
        title: "Feet",
      },
      {
        ID: "Cj",
        title: "Boots",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Ck",
        title: "Boot blacking",
        top: "Doing Blacking",
        bottom: "Having Boots Blacked",
      },
      {
        ID: "Cl",
        title: "Mirrors",
      },
      {
        ID: "Cm",
        title: "Semen play / cum fetish",
      },
      {
        ID: "Cn",
        title: "Frozen semen (inserting, saving, etc)",
      },
      {
        ID: "Co",
        title: "Pregnancy",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "Cp",
        title: "Impregnation (fantasy)",
        top: "Impregnating",
        bottom: "Being Impregnated",
      },
      {
        ID: "Cq",
        title: "Impregnation (actual)",
        top: "Impregnating",
        bottom: "Being Impregnated",
      },
      {
        ID: "Cr",
        title: "Feminization",
        top: "Feminizing",
        bottom: "Being Feminized",
      },
      {
        ID: "Cs",
        title: "Masculinization",
        top: "Masculinizing",
        bottom: "Being Masculinized",
      },
      {
        ID: "Ct",
        title: "Food play",
      },
      {
        ID: "Cu",
        title: "Nyotaimori",
        top: "Eater",
        bottom: "Plate",
      },
      {
        ID: "Cv",
        title: "Skinny-dipping",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "Cw",
        title: "Shaved hair (genital)",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "Cx",
        title: "Shaved hair (body)",
        top: "Partner",
        bottom: "Self",
      },
    ],
  },
  {
    title: "Voyeurism, Exhibitionism, and Humiliation",
    questions: [
      {
        ID: "EA",
        title: "Cross-dressing",
      },
      {
        ID: "EB",
        title: "Erotic dance (for audience)",
      },
      {
        ID: "EC",
        title: "Erotic dance (for partner)",
      },
      {
        ID: "ED",
        title: "Exhibitionism (friends)",
      },
      {
        ID: "EE",
        title: "Exhibitionism (strangers)",
      },
      {
        ID: "EF",
        title: "Forced nudity (private)",
        top: "Forcer",
        bottom: "Nude Person",
      },
      {
        ID: "EG",
        title: "Forced nudity (around friends)",
        top: "Forcer",
        bottom: "Nude Person",
      },
      {
        ID: "EH",
        title: "Forced nudity (around others/strangers)",
        top: "Forcer",
        bottom: "Nude Person",
      },
      {
        ID: "EI",
        title: "Humiliation (private)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "EJ",
        title: "Humiliation (public)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "EK",
        title: "Modeling for erotic photos",
        top: "Photographer",
        bottom: "Model",
      },
      {
        ID: "EL",
        title: "Posting erotic/dirty photos online",
        top: "Photographer",
        bottom: "Model",
      },
      {
        ID: "EM",
        title: "NSFW at work (wear a plug, dirty photos, etc)",
        top: "Partner at Work",
        bottom: "Self at Work",
      },
      {
        ID: "EN",
        title: "Outdoor scenes",
      },
      {
        ID: "EO",
        title: "Outdoor sex",
      },
      {
        ID: "EP",
        title: "Public exposure",
      },
      {
        ID: "EQ",
        title: "Public exposure (fetish/sex/swinger club)",
      },
      {
        ID: "ER",
        title: "Act of shaving (body hair)",
        top: "Shaving",
        bottom: "Being Shaved",
      },
      {
        ID: "ES",
        title: "Act of shaving (head hair)",
        top: "Shaving",
        bottom: "Being Shaved",
      },
      {
        ID: "ET",
        title: "Act of shaving (genital hair)",
        top: "Shaving",
        bottom: "Being Shaved",
      },
      {
        ID: "EU",
        title: "Waxing (hair removal)",
        top: "Waxing",
        bottom: "Being Waxed",
      },
      {
        ID: "EV",
        title: "Slutty clothing (private)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "EW",
        title: "Slutty clothing (public)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "EX",
        title: "Spitting",
        top: "Spitter",
        bottom: "Receiving Spit",
      },
      {
        ID: "EY",
        title: "Teasing",
        top: "Teaser",
        bottom: "Being Teased",
      },
      {
        ID: "EZ",
        title: "Verbal humiliation",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ea",
        title: "Video (recordings of you)",
      },
      {
        ID: "Eb",
        title: "Video (watching others)",
      },
      {
        ID: "Ec",
        title: "Voyeurism (watching others play)",
      },
      {
        ID: "Ed",
        title: "Voyeurism (watching your partner with others)",
        top: "Watching",
        bottom: "Being Watched",
      },
      {
        ID: "Ee",
        title: "Tampon Training (in ass)",
      },
      {
        ID: "Ef",
        title: "Objectification (art, furniture, etc)",
        top: "Objectifier",
        bottom: "Object",
      },
    ],
  },
  {
    title: "Bondage and Suspension",
    questions: [
      {
        ID: "GA",
        title: "Bondage (heavy)",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GB",
        title: "Bondage (light)",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GC",
        title: "Bondage (multi-day)",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GD",
        title: "Bondage (public, under clothing)",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GE",
        title: "Arm & leg sleeves (armbinders)",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GF",
        title: "Restrictive ropes",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GG",
        title: "Decorative ropes",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GH",
        title: "Rope body harness",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GI",
        title: "Breast/chest bondage",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GJ",
        title: "Chains",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GK",
        title: "Harnessing (leather)",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GL",
        title: "Harnessing (rope)",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GM",
        title: "Leather restraints",
        top: "Rigger",
        bottom: "Bound Person",
      },
      {
        ID: "GN",
        title: "Cuffs (general)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GO",
        title: "Cuffs (leather)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GP",
        title: "Cuffs (metal)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GQ",
        title: "Spreader bars",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GR",
        title: "Cages (locked inside of)",
      },
      {
        ID: "GS",
        title: "Cells/Closets (locked inside of)",
      },
      {
        ID: "GT",
        title: "Chastity devices (multi-day)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GU",
        title: "Chastity devices (short term)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GV",
        title: "Full head hoods",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GW",
        title: "Hoods",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "GX",
        title: "Suspension (hooks)",
        top: "Rigger",
        bottom: "Suspended Person",
      },
      {
        ID: "GY",
        title: "Suspension (rope, horizontal)",
        top: "Rigger",
        bottom: "Suspended Person",
      },
      {
        ID: "GZ",
        title: "Suspension (rope, upright)",
        top: "Rigger",
        bottom: "Suspended Person",
      },
      {
        ID: "Ga",
        title: "Gags (cloth)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gb",
        title: "Gags (inflatable)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gc",
        title: "Gags (phallic)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gd",
        title: "Gags (rubber)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Ge",
        title: "Gags (tape)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gf",
        title: "Straight jackets",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gg",
        title: "Manacles & Irons",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gh",
        title: "Stocks",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gi",
        title: "Mummification/Saran wrapping",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "Gj",
        title: "Immobilization",
        top: "Giving",
        bottom: "Being Immobile",
      },
      {
        ID: "Gk",
        title: "Sleepsacks",
      },
      {
        ID: "Gl",
        title: "Thumbcuffs (metal)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
    ],
  },
  {
    title: "Service and Behavior Restrictions",
    questions: [
      {
        ID: "IA",
        title: "Collars (worn in private)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "IB",
        title: "Collars (worn in public)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "IC",
        title: "Wearing symbolic jewelry",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "ID",
        title: "Following orders",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "IE",
        title: "Forced bed wetting",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IF",
        title: "Forced dressing",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IG",
        title: "Forced eating",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IH",
        title: "Forced masturbation",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "II",
        title: "Forced servitude",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IJ",
        title: "Forced orgasm",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IK",
        title: "Forced smoking",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IL",
        title: "Forced weight gain",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IM",
        title: "Forced weight loss",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IN",
        title: "Exercise (forced/required)",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IO",
        title: "Forced heterosexuality",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IP",
        title: "Forced homosexuality",
        top: "Forcer",
        bottom: "Being Forced",
      },
      {
        ID: "IQ",
        title: "Standing in corner",
        top: "Instructing",
        bottom: "Performing",
      },
      {
        ID: "IR",
        title: "Kneeling",
        top: "Instructing",
        bottom: "Performing",
      },
      {
        ID: "IS",
        title: "Service (general)",
        top: "Receiving",
        bottom: "Performing",
      },
      {
        ID: "IT",
        title: "Serving as a maid",
        top: "Beneficiary",
        bottom: "Being Maid",
      },
      {
        ID: "IU",
        title: "Housework (doing)",
        top: "Instructing",
        bottom: "Doing",
      },
      {
        ID: "IV",
        title: "Serving as art",
        top: "Viewing",
        bottom: "Being",
      },
      {
        ID: "IW",
        title: "Serving as ashtray",
        top: "Using",
        bottom: "Being",
      },
      {
        ID: "IX",
        title: "Serving as furniture",
        top: "Using",
        bottom: "Being",
      },
      {
        ID: "IY",
        title: "Serving as waitress/waiter",
        top: "Being Served",
        bottom: "Waiter/Waitress",
      },
      {
        ID: "IZ",
        title: "Serving orally (sexual)",
        top: "Receiving",
        bottom: "Giving",
      },
      {
        ID: "Ia",
        title: "Being serviced (sexual)",
        top: "Serviced",
        bottom: "Server",
      },
      {
        ID: "Ib",
        title: "Chores (domestic service)",
        top: "Giving",
        bottom: "Doing",
      },
      {
        ID: "Ic",
        title: "Licking",
        top: "Licker",
        bottom: "Licked",
      },
      {
        ID: "Id",
        title: "Manicures",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ie",
        title: "Massage",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "If",
        title: "Chauffeuring (driving)",
        top: "Driver",
        bottom: "Passenger",
      },
      {
        ID: "Ig",
        title: "Phone sex (commercial provider)",
        top: "Caller",
        bottom: "Operator",
      },
      {
        ID: "Ih",
        title: "Phone sex (serving Dom's / partner's friends)",
        top: "Caller",
        bottom: "Operator",
      },
      {
        ID: "Ii",
        title: "Phone sex (serving Dom / partner)",
        top: "Caller",
        bottom: "Operator",
      },
      {
        ID: "Ij",
        title: "Prostitution (actual, public or private)",
        top: '"John"',
        bottom: "Service Provider",
      },
      {
        ID: "Ik",
        title: "Prostitution (public pretense)",
        top: '"John"',
        bottom: "Service Provider",
      },
      {
        ID: "Il",
        title: "Free use fetish",
        top: "User",
        bottom: "Free to Use",
      },
      {
        ID: "Im",
        title: "Restrictive rules on behavior",
        top: "Rule Giver",
        bottom: "Being Restricted",
      },
      {
        ID: "In",
        title: "Eye contact restrictions",
        top: "Rule Giver",
        bottom: "Being Restricted",
      },
      {
        ID: "Io",
        title: "Enforced chastity",
        top: "Enforcer",
        bottom: "Being Chaste",
      },
      {
        ID: "Ip",
        title: "Orgasm control",
        top: "Controller",
        bottom: "Orgasmer",
      },
      {
        ID: "Iq",
        title: "Orgasm denial",
        top: "Denier",
        bottom: "Orgasmer",
      },
      {
        ID: "Ir",
        title: "Sexual deprivation (long term)",
        top: "Controller",
        bottom: "Deprived",
      },
      {
        ID: "Is",
        title: "Sexual deprivation (short term)",
        top: "Controller",
        bottom: "Deprived",
      },
      {
        ID: "It",
        title: "Speech restrictions (when, what)",
        top: "Rule Giver",
        bottom: "Being Restricted",
      },
      {
        ID: "Iu",
        title: "Sleep deprivation",
        top: "Controller",
        bottom: "Deprived",
      },
      {
        ID: "Iv",
        title: "Bathroom use control",
        top: "Controller",
        bottom: "Controlled",
      },
      {
        ID: "Iw",
        title: "Punishment ",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "Ix",
        title: "Having clothing chosen for you",
        top: "Chooser",
        bottom: "Wearer",
      },
      {
        ID: "Iy",
        title: "Having food chosen for you",
        top: "Chooser",
        bottom: "Eater",
      },
      {
        ID: "Iz",
        title: "Name change (for scene)",
      },
      {
        ID: "I0",
        title: "Name change (legal, permanent)",
      },
      {
        ID: "I1",
        title: "Persona training (in scene)",
        top: "Trainer",
        bottom: "Being Trained",
      },
      {
        ID: "I2",
        title: "Personality modification",
        top: "Trainer",
        bottom: "Being Trained",
      },
      {
        ID: "I3",
        title: "Lectures for misbehavior",
        top: "Lecturer",
        bottom: "Receiver",
      },
      {
        ID: "I4",
        title: "Supplying new partners",
        top: "Being Supplied",
        bottom: "Supplier",
      },
      {
        ID: "I5",
        title: "Serving other Doms (supervised)",
        top: "Dom",
        bottom: "Server",
      },
      {
        ID: "I6",
        title: "Serving other Doms (unsupervised)",
        top: "Dom",
        bottom: "Server",
      },
      {
        ID: "I7",
        title: "Given away to another Dom (perm)",
        top: "Giver",
        bottom: "Being Given",
      },
      {
        ID: "I8",
        title: "Given away to another Dom (temp)",
        top: "Giver",
        bottom: "Being Given",
      },
      {
        ID: "I9",
        title: "Given away to another Dom (for training)",
        top: "Giver",
        bottom: "Being Given",
      },
      {
        ID: "I-",
        title: "Harems (serving w/other subs)",
        top: "Harem Leader",
        bottom: "Harem Member",
      },
      {
        ID: "I_",
        title: "Competitions (with other Subs)",
        top: "Watching",
        bottom: "Competitor",
      },
      {
        ID: "JA",
        title: "Auctioned for charity",
        top: "Dom",
        bottom: "Being Auctioned",
      },
    ],
  },
  {
    title: "Impact Play",
    questions: [
      {
        ID: "KA",
        title: "Hair pulling",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KB",
        title: "Bruises",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KC",
        title: "Beating (soft)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KD",
        title: "Beating (hard)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KE",
        title: "Caning",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KF",
        title: "Wooden paddles",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KG",
        title: "Hairbrush spankings",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KH",
        title: "Spanking",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KI",
        title: "Over-the-knee spanking",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KJ",
        title: "Riding crops",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KK",
        title: "Single-tail whips (dragon tails, etc)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KL",
        title: "Leather straps",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KM",
        title: "Flogging",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KN",
        title: "Strapping (full body beating)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KO",
        title: "Whipping",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KP",
        title: "Cock flogging",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KQ",
        title: "Pussy/Clitoris flogging",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KR",
        title: "Pussy/Clitoris slapping",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KS",
        title: "Breast whipping",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KT",
        title: "Breast slapping",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "KU",
        title: "Face slapping",
        top: "Giving",
        bottom: "Receiving",
      },
    ],
  },
  {
    title: "Sensation Play",
    questions: [
      {
        ID: "MA",
        title: "Abrasion",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MB",
        title: "Aromas",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MC",
        title: "Asphyxiation",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MD",
        title: "Biting",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "ME",
        title: "Sensory deprivation",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MF",
        title: "Blindfolds",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "MG",
        title: "Choking",
        top: "Choker",
        bottom: "Being Choked",
      },
      {
        ID: "MH",
        title: "Gates of Hell (male)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "MI",
        title: "Hot oils (on genitals)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MJ",
        title: "Hot waxing",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MK",
        title: "Ice cubes",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "ML",
        title: "Ice packs",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MM",
        title: "Warmed glass or metal toys",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MN",
        title: "Cooled glass or metal toys",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MO",
        title: "Knife play",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MP",
        title: "Texture play",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MQ",
        title: "Scratching",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MR",
        title: "Cattle prod (electrical toy)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MS",
        title: "Violet Wand (electrical toy)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MT",
        title: "TENS unit (electrical toy)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "MU",
        title: "Breath control",
        top: "Controller",
        bottom: "Controlled",
      },
      {
        ID: "MV",
        title: "Tickling",
        top: "Tickler",
        bottom: "Being Tickled",
      },
      {
        ID: "MW",
        title: "Cupping",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "MX",
        title: "Fire play",
        top: "Giving",
        bottom: "Receiving",
      },
    ],
  },
  {
    title: "Age Play/Roleplay",
    questions: [
      {
        ID: "OA",
        title: "Age play (general)",
      },
      {
        ID: "OB",
        title: "Infantilism",
      },
      {
        ID: "OC",
        title: "Diapers (wearing)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "OD",
        title: "Diapers (wetting)",
        top: "Partner Wetting",
        bottom: "Wetting",
      },
      {
        ID: "OE",
        title: "Diapers (soiling)",
        top: "Partner Soiling",
        bottom: "Soiling",
      },
      {
        ID: "OF",
        title: "Childhood play (coloring, blocks, etc)",
      },
      {
        ID: "OG",
        title: "Teenager play",
      },
      {
        ID: "OH",
        title: "Daddy play",
      },
      {
        ID: "OI",
        title: "Mommy play",
      },
      {
        ID: "OJ",
        title: "Elderly play",
      },
    ],
  },
  {
    title: "Animal Roleplay",
    questions: [
      {
        ID: "QA",
        title: "Animal roles",
        top: "Handler",
        bottom: "Animal",
      },
      {
        ID: "QB",
        title: "Puppy play",
        top: "Handler",
        bottom: "Animal",
      },
      {
        ID: "QC",
        title: "Pony play",
        top: "Handler",
        bottom: "Animal",
      },
      {
        ID: "QD",
        title: "Kitten play",
        top: "Handler",
        bottom: "Animal",
      },
      {
        ID: "QE",
        title: "Furry play",
        top: "Handler",
        bottom: "Animal",
      },
      {
        ID: "QF",
        title: "Mouth bits",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
    ],
  },
  {
    title: "Body Part Focus/Torture",
    questions: [
      {
        ID: "SA",
        title: "Pain (mild)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "SB",
        title: "Pain (medium)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "SC",
        title: "Pain (severe)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "SD",
        title: "Clothespins",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SE",
        title: "Clothespin zipper",
        top: "Zipper Giver",
        bottom: "Wearing Zipper",
      },
      {
        ID: "SF",
        title: "Clit clamps (nipple clamp on clit)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SG",
        title: "Nipple clamps",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SH",
        title: "Nipple play",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "SI",
        title: "Nipple rings (piercings)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SJ",
        title: "Nipple suction cups (snake bite kit)",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SK",
        title: "Nipple weights",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SL",
        title: "Breast worship",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "SM",
        title: "Ball stretching",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SN",
        title: "Ball crushers",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SO",
        title: "Cock rings/straps",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
      {
        ID: "SP",
        title: "Cock and ball torture",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "SQ",
        title: "Cock worship",
        top: "Being Worshiped",
        bottom: "Worshiping",
      },
      {
        ID: "SR",
        title: "Pussy worship",
        top: "Being Worshiped",
        bottom: "Worshiping",
      },
      {
        ID: "SS",
        title: "Boot worship",
        top: "Being Worshiped",
        bottom: "Worshiping",
      },
      {
        ID: "ST",
        title: "Foot worship",
        top: "Being Worshiped",
        bottom: "Worshiping",
      },
      {
        ID: "SU",
        title: "High heel worship",
        top: "Being Worshiped",
        bottom: "Worshiping",
      },
      {
        ID: "SV",
        title: "High heel wearing",
        top: "Partner Wearing",
        bottom: "Wearing",
      },
    ],
  },
  {
    title: "Body Modification",
    questions: [
      {
        ID: "UA",
        title: "Branding",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "UB",
        title: "Cutting",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "UC",
        title: "Injections",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "UD",
        title: "Piercing (permanent)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "UE",
        title: "Piercing (temporary, play-pierce)",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "UF",
        title: "Plastic surgery",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "UG",
        title: "Scarification",
        top: "Giving",
        bottom: "Receiving",
      },
      {
        ID: "UH",
        title: "Tattooing",
        top: "Giving",
        bottom: "Receiving",
      },
    ],
  },
  {
    title: "Bodily Fluids and Related",
    questions: [
      {
        ID: "WA",
        title: "Enemas (for cleansing)",
        top: "Giving",
        bottom: "Taking",
      },
      {
        ID: "WB",
        title: "Enemas (retention/punishment)",
        top: "Giving",
        bottom: "Taking",
      },
      {
        ID: "WC",
        title: "Brown showers (scat)",
        top: "Giving",
        bottom: "Taking",
      },
      {
        ID: "WD",
        title: "Golden showers (aka watersports)",
        top: "Giving",
        bottom: "Taking",
      },
      {
        ID: "WE",
        title: "Serving as toilet (feces)",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "WF",
        title: "Serving as toilet (urine)",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "WG",
        title: "Swallowing feces",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "WH",
        title: "Swallowing urine",
        top: "Partner",
        bottom: "Self",
      },
      {
        ID: "WI",
        title: "Blood play",
      },
      {
        ID: "WJ",
        title: "Menstruation play",
      },
    ],
  },
];
