import { useReducer } from "react";

import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";

import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";

import { Header, Body } from "../../utils/formats";

export default function VanillaLife() {
  const [expanded, toggleExpanded] = useReducer((state) => !state, true);

  return (
    <>
      <Box
        sx={{
          display: "flex",
          justifyContent: "center",
        }}
      >
        <Button
          color="white"
          sx={{ textTransform: "unset", padding: "0px" }}
          onClick={toggleExpanded}
        >
          {expanded ? <ExpandLessIcon /> : <ExpandMoreIcon />}
          <Typography variant="h4" sx={{ padding: "0px 8px" }}>
            Vanilla Life
          </Typography>
          {expanded ? <ExpandLessIcon /> : <ExpandMoreIcon />}
        </Button>
      </Box>
      {expanded && (
        <>
          <Body>
            Oh god, I hate talking about myself but I feel like I should so I
            can give you, lovely reader, a feel for who I am outside of kink. I
            like to get to know play partners a bit outside of the context of
            kink as well because people are cool and fun and interesting, so
            yeah... hopefully you feel the same? It's totally fine if you don't,
            but like... why? Do you see your partners as objects? Idk, if you do
            maybe we should chat because I'd like to unpack that a bit to get a
            different perspective from my own.
          </Body>

          <Header>Nerd Shit (Computers)</Header>
          <Body>
            People call me a nerd, I think that label is bullshit and
            nondescriptive. What is a jock but a sports nerd? The only way to
            not be a nerd about at least something is to have no passion. So I
            guess people say I'm passionate? I dunno, now we're just getting
            into the nuances of how others see me vs. my own self-image.
            Aaanyway... I work a software development job and have some side
            projects that I'm happy to talk about. I'm interested in the fields
            of computer graphics, machine learning, and computer vision. I
            taught 3D graphics and my research was in ML/vision for kinesiology,
            which is kinda neat, kinda dorky, and just kinda weird. I also think
            simulations are pretty cool; I did some work on humanoid robotics
            simulations, even writing a senior-level university course on the
            topic. I like listening to people talk about cybersecurity and even
            thought about pursuing this field in college but had a professor who{" "}
            <em>really</em> fucking steered me away from it. Given the amount of
            AI slop code and vulnerabilities getting mindlessly generated by
            wannabe project managers with AI tools calling themselves "vibe
            coders", who knows, maybe that's an area I'll start poking at again.
            Speaking of AI, I have ✨opinions✨ about AI that I could probably
            talk about for hours, but like... fuck typing all that out. I'm not
            drunk or insane enough to do that. I love talking about this stuff,
            but I'm a little shy so you might need to kick things off 😅
          </Body>

          <Header>Interlude: Climbing</Header>
          <Body>
            Like many software engineers, to keep active I prefer the sport
            where I face a wall and don't have to interact with anyone... that's
            right, rock climbing. Jokes aside, the social aspect of the sport is
            really great. If you haven't tried it before, I'd highly recommend
            it! Stick with it for a little while and you'll find a super
            supportive community and people who you don't really know by name,
            but you absolutely know them by face. The puzzle solving parts of
            the sport also scratch the brain itch in a fun way. Figuring out
            what sequences will simply get you to the top and which sequences
            will work particularly well with your body to get you to the top
            efficiently are two totally different things. It also varies by
            body, so what works for your friend may not work for you, which is
            another fun aspect in my opinion.
          </Body>

          <Header>More Nerd Shit (Media)</Header>
          <Body>
            I also like to consume certain forms of media. Anime? Hell yeah!
            Video games? I'm a little picky and could stand to branch out more,
            but hell yeah! Movies? I'm mostly into horror but hell yeah! Music
            is probably the biggest form of media I consume. Growing up I was
            around music a lot. I was in various types of bands in school
            (concert, marching, jazz, etc.), but when I got to college I had to
            give it up a bit. I still listen to it a lot and have a fairly wide
            breadth of stuff I listen to, so I'm always happy to give
            recommendations. I'm not a huuuuge fan of trying to split things
            into super specific subgenres (I used to do that, and I was a
            pretentious prick for it). I know that's a pretty big thing in metal
            and EDM communities, but it's just not my thing. I like my beep boop
            music and I like my screamy angry music and I don't care what
            fucking label you want to put on it. Often artists are drawing
            inspiration from many sources, so slapping a single label on them is
            doing them a disservice in my opinion. Honestly, I might go ahead
            and make a page specifically for music recommendations. Music is a
            good topic for connecting with others, so I'm always down to chat
            music and listen to others' recommendations.
          </Body>
        </>
      )}
    </>
  );
}
